# Generated by Django 2.2.2 on 2019-06-17 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20, unique=True)),
                ('service_ip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contract', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_category', models.CharField(choices=[('Web', 'Web Application'), ('And', 'Android Mobile App'), ('iOS', 'iOS Mobile App'), ('C/S', 'Client & Server Program')], default='Web', max_length=5)),
                ('vul_id', models.CharField(max_length=10)),
                ('vul_name', models.CharField(max_length=50)),
                ('vul_level', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('I', 'Information')], max_length=3)),
                ('vul_description', models.CharField(max_length=100)),
                ('vul_countermeasure', models.TextField(max_length=300)),
                ('vul_countermeasure_code', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Projectresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_url', models.CharField(max_length=100)),
                ('vul_param', models.CharField(max_length=50)),
                ('vul_comment', models.CharField(max_length=300)),
                ('vul_cause_comment', models.TextField(max_length=300)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Assets')),
                ('vul_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Vulnerabilities')),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='service_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Owners'),
        ),
    ]
