# Generated by Django 2.2.2 on 2019-06-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfill_vul_param', models.CharField(max_length=50)),
                ('fulfill_vul_evi', models.TextField(max_length=300)),
                ('fulfill_vul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projectresult')),
            ],
        ),
    ]
