# Generated by Django 2.2.2 on 2019-07-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_fulfillment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name_plural': '1. 자산관리'},
        ),
        migrations.AlterModelOptions(
            name='fulfillment',
            options={'verbose_name_plural': '5. 이행점검 결과'},
        ),
        migrations.AlterModelOptions(
            name='owners',
            options={'verbose_name_plural': '2. 담당자관리'},
        ),
        migrations.AlterModelOptions(
            name='projectresult',
            options={'verbose_name_plural': '4. 진단결과'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilities',
            options={'verbose_name_plural': '3. 취약점 관리'},
        ),
        migrations.AddField(
            model_name='assets',
            name='service_domain',
            field=models.CharField(default=('www.naver.com', 'www.joara.com'), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='service_info_db',
            field=models.CharField(default='linux', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='service_info_os',
            field=models.CharField(default='linux', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='service_info_web',
            field=models.CharField(default='apache', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='vul_category',
            field=models.CharField(choices=[('Web', 'Web Application'), ('And', 'Android Mobile App'), ('iOS', 'iOS Mobile App'), ('C/S', 'Client & Server Program')], default='Web', max_length=5, verbose_name='취약점 구분'),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='vul_countermeasure',
            field=models.TextField(max_length=300, verbose_name='취약점 조치방법'),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='vul_countermeasure_code',
            field=models.TextField(max_length=300, verbose_name='취약점 조치 샘플코드'),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='vul_description',
            field=models.CharField(max_length=100, verbose_name='취약점 설명'),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='vul_id',
            field=models.CharField(max_length=10, verbose_name='취약점 ID'),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='vul_level',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('I', 'Information')], max_length=3, verbose_name='위험도'),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='vul_name',
            field=models.CharField(max_length=50, verbose_name='취약점명'),
        ),
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_startdate', models.DateField()),
                ('project_enddate', models.DateField()),
                ('project_price', models.IntegerField()),
                ('project_MM', models.FloatField(max_length=12)),
                ('project_description', models.TextField(max_length=200)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Owners')),
            ],
            options={
                'verbose_name_plural': '3. 프로젝트 관리',
            },
        ),
    ]
