# Generated by Django 2.2.2 on 2019-07-12 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190712_0424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fulfillment',
            options={'verbose_name_plural': '6. 이행점검 결과'},
        ),
        migrations.AlterModelOptions(
            name='projectmanagement',
            options={'verbose_name_plural': '4. 프로젝트 관리'},
        ),
        migrations.AlterModelOptions(
            name='projectresult',
            options={'verbose_name_plural': '5. 진단결과'},
        ),
        migrations.AddField(
            model_name='projectresult',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectManagement'),
            preserve_default=False,
        ),
    ]
