# Generated by Django 2.2.2 on 2019-07-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190712_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='fulfill_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='fulfill_vul_complete',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
