# Generated by Django 2.2.2 on 2019-07-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190712_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='service_domain',
            field=models.CharField(max_length=50, verbose_name='서비스URL'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='service_info_db',
            field=models.CharField(max_length=20, verbose_name='구성_DB종류'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='service_info_os',
            field=models.CharField(max_length=20, verbose_name='구성_OS종류'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='service_info_web',
            field=models.CharField(max_length=20, verbose_name='구성_WEB종류'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='service_ip',
            field=models.CharField(max_length=20, verbose_name='서비스IP'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='service_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='서비스명'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='service_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Owners', verbose_name='서비스 소유자'),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='fulfill_count',
            field=models.IntegerField(verbose_name='이행점검 차수'),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='fulfill_vul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projectresult', verbose_name='이행대상'),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='fulfill_vul_complete',
            field=models.IntegerField(verbose_name='조치 파라메터 수'),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='fulfill_vul_evi',
            field=models.TextField(max_length=300, verbose_name='조치완료 확인'),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='fulfill_vul_param',
            field=models.CharField(max_length=50, verbose_name='조치완료 파라메터'),
        ),
        migrations.AlterField(
            model_name='owners',
            name='contract',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='owners',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='owners',
            name='name',
            field=models.CharField(max_length=20, verbose_name='담당자명'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='project_MM',
            field=models.FloatField(max_length=12, verbose_name='프로젝트 투입공수'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='project_description',
            field=models.TextField(max_length=200, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='project_enddate',
            field=models.DateField(verbose_name='프로젝트 종료일'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Owners', verbose_name='담당자명'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='project_name',
            field=models.CharField(max_length=50, verbose_name='프로젝트명'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='project_price',
            field=models.IntegerField(verbose_name='프로젝트 금액'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='project_startdate',
            field=models.DateField(verbose_name='프로젝트 시작일'),
        ),
        migrations.AlterField(
            model_name='projectresult',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectManagement', verbose_name='프로젝트명'),
        ),
        migrations.AlterField(
            model_name='projectresult',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Assets', verbose_name='점검대상 서비스명'),
        ),
        migrations.AlterField(
            model_name='projectresult',
            name='vul_cause_comment',
            field=models.TextField(max_length=300, verbose_name='기타설명'),
        ),
        migrations.AlterField(
            model_name='projectresult',
            name='vul_comment',
            field=models.TextField(max_length=300, verbose_name='취약점 도출방법'),
        ),
        migrations.AlterField(
            model_name='projectresult',
            name='vul_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Vulnerabilities', verbose_name='취약점 명'),
        ),
        migrations.AlterField(
            model_name='projectresult',
            name='vul_param',
            field=models.CharField(max_length=50, verbose_name='취약한 파라메터'),
        ),
        migrations.AlterField(
            model_name='projectresult',
            name='vul_url',
            field=models.CharField(max_length=100, verbose_name='취약한 URL'),
        ),
    ]
